export const themes = [
    {
        id: 'deep-blue',
        name: 'آبی دریایی',
        primary: '#0d3b66',
        accent: '#f9c74f',
        surface: '#ffffff',
        background: '#e8f0ff',
        soft: '#f4f9ff',
    },
    {
        id: 'midnight',
        name: 'شبانه',
        primary: '#1a1b27',
        accent: '#80d0c7',
        surface: '#1f2330',
        background: '#0d1117',
        soft: '#131722',
    },
    {
        id: 'sunrise',
        name: 'طلوع',
        primary: '#9a031e',
        accent: '#ffba08',
        surface: '#fff8f1',
        background: '#fff3e0',
        soft: '#ffe8cc',
    },
    {
        id: 'emerald',
        name: 'زمردی',
        primary: '#064e3b',
        accent: '#34d399',
        surface: '#f0fdf4',
        background: '#e7f7ed',
        soft: '#d9f2e3',
    },
    {
        id: 'lavender',
        name: 'اسطوخودوس',
        primary: '#3b2c85',
        accent: '#b388eb',
        surface: '#f7f4ff',
        background: '#ede8ff',
        soft: '#e2dbff',
    },
    {
        id: 'sandstone',
        name: 'سنگی',
        primary: '#6f4e37',
        accent: '#f4a261',
        surface: '#fffaf3',
        background: '#f3e9dd',
        soft: '#ece1d4',
    },
    {
        id: 'gelato',
        name: 'ژلاتو',
        primary: '#4281a4',
        accent: '#e6b89c',
        surface: '#ead2ac',
        background: '#fe938c',
        soft: '#9cafb7',
    },
    {
        id: 'tangerine',
        name: 'نارنگی',
        primary: '#f06543',
        accent: '#f09d51',
        surface: '#E8E9EB',
        background: '#313638',
        soft: '#e0dfd5',
    },
    {
        id: 'pastel',
        name: 'پاستیل',
        primary: '#EFA7A7',
        accent: '#FFD972',
        surface: '#C7EAE4',
        background: '#FCBCB8',
        soft: '#A7E8BD',
    },
];

export default themes;